### ISSUE TITLE
plugin not defined

### ISSUE THREAD

**Issue by tommaso82** [TangoCash/lcd4linux#1]
qnaplog plugin is not defined in plugin.c

apart from this once the plugin is defined in plugin.c and compiled everything works correctly except for an error that the plugin returns but which does not seem to affect its correct functioning

**Comment by BPanther** [comment]
This is only a fork with small changes for SH4/VU+. The problem therefore lies more with the original GIT/SVN. Here no one use qnaplog. We use this only for Samsung SPF or Pearl DPF.
